# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7b8a0e7bd270cac3a6ce5ac4b0a23812e5dcbd673ca6358dcec20765900dadb02b1c4518079e66df30469d01c45b415bc7c208339c50d6100dd6fee1fd85a43

test:
  secret_key_base: e7d355c0aff651259be1762a87283fa4d2d904fa000899bf504a8f54f1fa63c1ad989974a33e3c7aa2c569c2cfc1140f4f3350172769a96f654c1d24e4b011e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
